CREATE TABLE DAEJEON_ENERGY (
        PK_CD NUMBER,
        LOTNO_ADDR VARCHAR2(4000),
        ROAD_NM_ADDR VARCHAR2(4000),
        SGNG_CD VARCHAR2(4000),
        STDG_CD VARCHAR2(4000),
        LOTNO_MNO VARCHAR2(4000),
        LOTNO_SNO VARCHAR2(4000),
        GPS_LOT VARCHAR2(4000),
        GPS_LAT VARCHAR2(4000),
        STNDD_YR VARCHAR2(4000),
        USE_MM VARCHAR2(4000),
        ELRW_USQNT VARCHAR2(4000),
        CTY_GAS_USQNT VARCHAR2(4000),
        SUM_NRG_USQNT VARCHAR2(4000),
        ELRW_TOE_USQNT VARCHAR2(4000),
        CTY_GAS_TOE_USQNT VARCHAR2(4000),
        SUM_NRG_TOE_USQNT VARCHAR2(4000),
        ELRW_GRGS_DSAMT VARCHAR2(4000),
        CTY_GAS_GRGS_DSAMT VARCHAR2(4000),
        SUM_GRGS_DSAMT VARCHAR2(4000)
);

ALTER TABLE DAEJEON_ENERGY ADD CONSTRAINT PK_ENERGY 
PRIMARY KEY(PK_CD);

create table DAEJEON_ENERGY1 
as
SELECT LOTNO_ADDR, 
    ROAD_NM_ADDR,
    SGNG_CD,
    STDG_CD,
    LOTNO_MNO,
    LOTNO_SNO,
    GPS_LOT,
    GPS_LAT,
    STNDD_YR, -- 기준년도
    USE_MM, -- 사용월
    TO_NUMBER(ELRW_USQNT) as ELRW_USQNT, -- 전력사용량
    TO_NUMBER(CTY_GAS_USQNT) as CTY_GAS_USQNT, -- 도시가스 사용량
    TO_NUMBER(SUM_NRG_USQNT) as SUM_NRG_USQNT,
    TO_NUMBER(ELRW_TOE_USQNT) as ELRW_TOE_USQNT,
    TO_NUMBER(CTY_GAS_TOE_USQNT) as CTY_GAS_TOE_USQNT,
    TO_NUMBER(SUM_NRG_TOE_USQNT) as SUM_NRG_TOE_USQNT,
    TO_NUMBER(ELRW_GRGS_DSAMT) as ELRW_GRGS_DSAMT,
    TO_NUMBER(CTY_GAS_GRGS_DSAMT) as CTY_GAS_GRGS_DSAMT,
    TO_NUMBER(SUM_GRGS_DSAMT) as SUM_GRGS_DSAMT
from DAEJEON_ENERGY
WHERE REGEXP_LIKE(ELRW_USQNT, '^\d+(\.\d+)?$')
AND  REGEXP_LIKE(CTY_GAS_USQNT, '^\d+(\.\d+)?$')
AND  REGEXP_LIKE(SUM_NRG_USQNT, '^\d+(\.\d+)?$')
AND  REGEXP_LIKE(ELRW_TOE_USQNT, '^\d+(\.\d+)?$')
AND  REGEXP_LIKE(CTY_GAS_TOE_USQNT, '^\d+(\.\d+)?$')
AND  REGEXP_LIKE(SUM_NRG_TOE_USQNT, '^\d+(\.\d+)?$')
AND  REGEXP_LIKE(ELRW_GRGS_DSAMT, '^\d+(\.\d+)?$')
AND  REGEXP_LIKE(CTY_GAS_GRGS_DSAMT, '^\d+(\.\d+)?$')
AND  REGEXP_LIKE(SUM_GRGS_DSAMT, '^\d+(\.\d+)?$')
;

COMMENT ON COLUMN DAEJEON_ENERGY1.lotno_addr IS '지번주소';
COMMENT ON COLUMN DAEJEON_ENERGY1.lotno_mno IS '지번본번';
COMMENT ON COLUMN DAEJEON_ENERGY1.lotno_sno IS '지번부번';
COMMENT ON COLUMN DAEJEON_ENERGY1.road_nm_addr IS '도로명주소';
COMMENT ON COLUMN DAEJEON_ENERGY1.sgng_cd IS '시군구코드';
COMMENT ON COLUMN DAEJEON_ENERGY1.stdg_cd IS '법정동코드';
COMMENT ON COLUMN DAEJEON_ENERGY1.gps_lot IS 'GPS경도';
COMMENT ON COLUMN DAEJEON_ENERGY1.gps_lat IS 'GPS위도';
COMMENT ON COLUMN DAEJEON_ENERGY1.stndd_yr IS '기준년도';
COMMENT ON COLUMN DAEJEON_ENERGY1.use_mm IS '사용월';
COMMENT ON COLUMN DAEJEON_ENERGY1.elrw_usqnt IS '전력사용량';
COMMENT ON COLUMN DAEJEON_ENERGY1.cty_gas_usqnt IS '도시가스사용량';
COMMENT ON COLUMN DAEJEON_ENERGY1.sum_nrg_usqnt IS '합계에너지사용량';
COMMENT ON COLUMN DAEJEON_ENERGY1.elrw_toe_usqnt IS '전력TOE사용량';
COMMENT ON COLUMN DAEJEON_ENERGY1.CTY_GAS_TOE_USQNT IS '도시가스TOE사용량';
COMMENT ON COLUMN DAEJEON_ENERGY1.sum_nrg_toe_usqnt IS '합계에너지TOE사용량';
COMMENT ON COLUMN DAEJEON_ENERGY1.elrw_grgs_dsamt IS '전력온실가스배출량';
COMMENT ON COLUMN DAEJEON_ENERGY1.cty_gas_grgs_dsamt IS '도시가스온실가스배출량';
COMMENT ON COLUMN DAEJEON_ENERGY1.sum_grgs_dsamt IS '합계온실가스배출량';

CREATE TABLE SGNG_STDG_NM
AS
SELECT distinct SGNG_NM, SGNG_CD, stdg_nm, stdg_cd
FROM(
SELECT TRIM(SUBSTR(lotno_addr, 6,4)) as SGNG_NM, SGNG_CD,
       TRIM(SUBSTR(lotno_addr, 10,3)) as stdg_nm
       , stdg_cd
FROM daejeon_energy1)
WHERE SGNG_NM IN ('서구','동구','중구')
UNION
SELECT distinct SGNG_NM, SGNG_CD, stdg_nm, stdg_cd
FROM(
SELECT TRIM(SUBSTR(lotno_addr, 6,4)) as SGNG_NM, SGNG_CD,
       TRIM(SUBSTR(lotno_addr, 11,3)) as stdg_nm
       , stdg_cd
FROM daejeon_energy1)
WHERE SGNG_NM IN ('대덕구','유성구')
order by 1
;

create table TEAM1_ENERGY
as
SELECT LOTNO_ADDR, 
    ROAD_NM_ADDR,
    a.SGNG_CD,
    b.sgng_nm,
    a.STDG_CD,
    b.stdg_nm,
    LOTNO_MNO,
    LOTNO_SNO,
    GPS_LOT,
    GPS_LAT,
    STNDD_YR, -- 기준년도
    USE_MM, -- 사용월
    ELRW_USQNT, -- 전력사용량
    CTY_GAS_USQNT, -- 도시가스 사용량
    SUM_NRG_USQNT,
    ELRW_TOE_USQNT,
    CTY_GAS_TOE_USQNT,
    SUM_NRG_TOE_USQNT,
    ELRW_GRGS_DSAMT,
    CTY_GAS_GRGS_DSAMT,
    SUM_GRGS_DSAMT
from DAEJEON_ENERGY1 a, sgng_stdg_nm b
WHERE a.SGNG_CD = b.sgng_cd
AND  a.stdg_cd = b.stdg_cd;

-- id="getAllData"
SELECT 
    STNDD_YR,
    USE_MM,
    SUM(ELRW_USQNT) as ELRW_USQNT,  
    SUM(CTY_GAS_USQNT) as CTY_GAS_USQNT,
    SUM(SUM_NRG_USQNT) as SUM_NRG_USQNT 
FROM daejeon_energy1
WHERE STNDD_YR = '2022'
GROUP BY STNDD_YR, USE_MM
ORDER BY STNDD_YR, TO_NUMBER(USE_MM);


